### ISSUE TITLE
Add an option to automatically trim strings

### ISSUE THREAD

**Issue by jeremyhalin** [Synthoid/ExportSheetData#121]
Hi,
Thanks for this great plugin ! 👍 

I'm missing only one feature that I've used myself with a custom script to export to json, the possibility to trim columns in string format, so I don't end up with words or sentences with spaces at start or end of the cell.

I would be very happy to contribute and open a pull request !

**Comment by Synthoid** [comment]
Glad you are enjoying ESD!

I thought I had already implemented this but it turns out that was only the case if you were exporting cells as arrays. I went ahead and added support for trimming strings since I'm currently refactoring some of the export code so that should be in the next release. Thanks for catching this!
