### ISSUE TITLE
(General) Addon Scope/Permissions

### ISSUE THREAD

**Issue by ayajsgs** [Synthoid/ExportSheetData#128]
I have been using this addon frequently, however my company has revoked access to it because of the scope it asks for - permission to all drive files. 

Is this a limitation on Google's part where you can't set the permissions more granularly? 

It would be great to use this addon, but without any changes to the permissions I doubt the company will allow to use it.

**Comment by Synthoid** [comment]
This is a question that has [come up before](https://github.com/Synthoid/ExportSheetData/issues/81) and probably means I should create an FAQ for it. Essentially, ESD needs access to Drive in order to create the exported `.xml` and `.json` files. Unfortunately, apps script scopes are pretty broad so I can't just request permission to create or read specific files, it's an all or nothing approach. There's not really anything I can do to request more granular access and I have tried to keep scopes to the bare minimum needed for ESD to function.

You can look through the source code here to see what ESD is doing if that will help ease concerns, and there's always the nuclear option of forking ESD and using your own version internally. I don't recommend making your own version though since that will cut you off from automatic updates. I can guarantee that ESD is safe to use and that it doesn't do anything nefarious, but I understand that seeing the "access to all drive files" permission is scary. Unfortunately there's just not much I can to to address that.

**Comment by Synthoid** [comment]
Closing this issue as it has been addressed.
