### ISSUE TITLE
Problem with the export of nested elements since last update

### ISSUE THREAD

**Issue by Winnao** [Synthoid/ExportSheetData#137]
Hello !

I'm using ExportSheetData with nested elements since a year or two, and since the last update, the export is not right :/

Before the update, we had [this](https://i.gyazo.com/340d50344a1f53c09e578135a9a86635.png)
And now [this](https://i.gyazo.com/b353f0eb1b521726f9133c2e328f971b.png)

I don't understand why it doesn't work now :c
I'll put a simplified version here of my google sheet [here](https://docs.google.com/spreadsheets/d/1HwL6fWAIIsPk9za-eOtp8VtN52bZ4hYSql-dlD_itEA/edit?usp=sharing)

Thank you !

**Comment by Synthoid** [comment]
I copied your linked sheet and adjusted settings to get this output:

```
{
  "MetaData": {
    "Joueur": "Politique2"
  },
  "UI_IntroLetter": [
    {
      "CharacterID": "Commissaire",
      "TextID": "UI_IntroLetter_Commissaire_1",
      "audioID": "UI_IntroLetter_Commissaire_1"
    }
  ]
}
```

Which seems to line up with your previous data. My guess is that you were exporting the sheets as arrays but that setting was disabled at some point? The {#SHEET}{#ROW} key values only really work when exporting a sheet as an array since they are assigning the key to the element at index {#ROW} in the {#SHEET} array.

In any case, the above data was generated by renaming `UI_IntroLetter` to `JA_UI_IntroLetter` and enabling the [array prefix option](https://github.com/Synthoid/ExportSheetData/blob/master/docs/json/arrayprefix.md). Nested elements and Ignore empty cells were also enabled.

**Comment by Synthoid** [comment]
Also, you can simplify your sheet keys by enabling the [Nested array prefix option](https://github.com/Synthoid/ExportSheetData/blob/master/docs/json/nestedarrayprefix.md) and adding the `NA_` prefix to your tab name. This will let you remove the {#SHEET}{#ROW} prefixes from all of your keys.

Sorry it took a few days to get back to you! Hopefully this helps sort things out!

**Comment by Synthoid** [comment]
Closing this issue as I believe I have answered the question and the thread has been quiet for about a week.

**Comment by Synthoid** [comment]
Closing this issue as I believe I have answered the question and the thread has been quiet for about a week.
