### ISSUE TITLE
App is blocked because it tried to gain sensitive information

### ISSUE THREAD

**Issue by akerson** [Synthoid/ExportSheetData#163]
Been using this extension for years, it now doesn't work.

![image-8](https://github.com/Synthoid/ExportSheetData/assets/5715298/b1ba82d9-9717-4be1-a81c-9e53defb667d)

Google suggests the security feature improvements of Google has broken it. Any chance we could get a fix??

**Comment by vovabob** [comment]
Yes. Same thing.

**Comment by Synthoid** [comment]
Sorry, missed the initial comment here. I'll take a look and see what I can do!

**Comment by akerson** [comment]
Hi!

1. Yes there's three of us, we use it to development the json exports for our video game. One person is able to use it no problem so this tracks with what you are suggesting.
2. Personal Gmail accounts
3. Chrome in all three cases
4. USA for all three

We'll try having user 1 sign out and attempt again. It's a bit of a pain as sheets is tied to logging into everything with your Google account but it's probably more manageable than not having access to this tool as it's very unique.

**Comment by akerson** [comment]
Hello,

I am now owner of this sheet. I cannot install the extension. I'm assuming if you have it installed already there is no issues. Same error as before.

Maybe something like this would help?
https://developers.google.com/apps-script/guides/services/authorization#manual_authorization_scopes_forand

**Comment by Synthoid** [comment]
Hmm, do you already have ESD installed for your account? Or are you attempting to install it now?

If you already have it installed, are you able to make a new sheet and export JSON/XML from that?

**Comment by Synthoid** [comment]
Actually, I just tried doing so with my work account and I saw the blocked warning too...

I may need to update the Google Cloud Project for ESD to ensure its scopes are still correct. It could be that Google doesn't like granting access to Drive for file management purposes anymore, or at least has stricter scopes for it.

**Comment by Synthoid** [comment]
I think I have to do some OAuth verification steps on the project to fix this issue. That will require some web work on my end. This will take me a couple days due to my upcoming schedule unfortunately.

I will try to have the issue resolved ASAP. Sorry for the inconvenience!

**Comment by Synthoid** [comment]
Alright, I have ESD resubmitted for verification. Had to do a surprising amount of web dev and video production to verify an open source add-on, but hopefully it will be back up soon.

**Comment by Synthoid** [comment]
Quick update. I've been back and forth with Google's verification team this past week. I believe I've ironed out the last of their concerns with the latest round of revisions so hopefully the next time I hear from them it will be them approving everything.

**Comment by akerson** [comment]
Awesome keep us posted! Appreciate helping all of us out we love this addon 🥰

**Comment by khambadkone** [comment]
@Synthoid thanks for following up on this.  We are still facing this issue ; do you mean that your fix in https://github.com/Synthoid/ExportSheetData/issues/163#issuecomment-2227441128 is yet to be reviewed by Google, and once it is, we wont have this issue ?

Other than signing out of all other accounts, what is the known workaround until then?

**Comment by Synthoid** [comment]
To clarify, I have made requested revisions to various ESD resources and I am currently waiting to hear back from Google.

The turnaround on that is usually 24-72 hours so I should hopefully hear back within the next day.

Until I resolve the verification issues, there doesn't really seem to be a great workaround unfortunately. From my understanding, only around 100 people could actively choose to bypass the warning and that was probably a first come, first served situation.

If you can wait, I believe this will be resolved this week, ideally after this latest round of revisions. Barring some needling from Google's verification team...

I'm sorry I've let ESD languish and get into this state. I should have cleaned house months ago to prevent a lapse in service.

**Comment by BizarreFog** [comment]
> To clarify, I have made requested revisions to various ESD resources and I am currently waiting to hear back from Google.
> 
> The turnaround on that is usually 24-72 hours so I should hopefully hear back within the next day.
> 
> Until I resolve the verification issues, there doesn't really seem to be a great workaround unfortunately. From my understanding, only around 100 people could actively choose to bypass the warning and that was probably a first come, first served situation.
> 
> If you can wait, I believe this will be resolved this week, ideally after this latest round of revisions. Barring some needling from Google's verification team...
> 
> I'm sorry I've let ESD languish and get into this state. I should have cleaned house months ago to prevent a lapse in service.

Thanks for working through this to get it back up! Love your tool and am excited to pick it back up once Google approves it

**Comment by Synthoid** [comment]
So... some good news, and some bad news. The good news is that ESD has cleared Google's verification process!

The bad news is there is apparently another step. ESD has to clear a [CASA assessment](https://appdefensealliance.dev/casa) by a trusted third party. My initial look into Google's provided resources is not looking great. To even get a CASA assessment it's looking like I'd need to shell out $500+. That would become an annual expense as the evaluation has to happen every year... Even worse, the best evaluation process that gives maximum confidence for the application's security is a whopping $3000+ annually.

I'm going to look into my options here to see if I can get an exemption since it's just an Apps Script add-on that isn't storing user data and there were such exceptions in the past. This certainly wasn't part of the verification before but if it is indeed required now... I'm not sure that is an expense I can handle. The $3000+ evaluation absolutely isn't.

For the time being, that does mean ESD will be down for a little while longer. I'm sorry for the delay.

**Comment by Synthoid** [comment]
After looking into it some more, I may be able to avoid the whole CASA process as that is only required because ESD requests root Drive authorization for some processes.

Specifically the "Replace existing file(s)" option is the main thing using that scope to streamline workflows. I think I'll have to rework that so users have to select a file to replace instead of automatically clearing files in the export folder. It's a worse workflow, but that should mean ESD  will not cost me $3000+ a year...

**Comment by Synthoid** [comment]
![vb-brock-coffee](https://github.com/user-attachments/assets/e69b50af-c325-47e4-9a33-08804b8271af)

Quick update. I've been banging my head against my keyboard this weekend trying to get things working. Unfortunately the scope issue goes deeper than I thought and all of the existing `DriveApp` code ESD uses to create, not just update/replace, JSON/XML files require the restricted `auth/drive` scope. This is not viable as it means I'll have to go through the CASA evaluation every year.

The most promising approach seems to be migrating over to the [advanced Drive service](https://developers.google.com/apps-script/advanced/drive) so I can use the reduced `auth/drive.file` scope. I've made some minor progress on that, but it's looking like I'll be enduring some trial and error to get this fully working.

**Comment by sebinfinity** [comment]
@Synthoid Thank you for looking into this issue. The issue is also happening on my end.

Looking forward to being able to use your amazing plugin again!

**Comment by Synthoid** [comment]
Alright, time for another quick good news/bad news update.

The good news, **I have file exports working again!** The migration over to the advanced Drive service to create files was painful, but with enough persistence I've bashed that brick wall down.

The bad news, ESD in general is going to be less user friendly going forward and I'm probably going to have to rip out file replacement and export folder customization. The more restricted `auth/drive.file` scope pretty much only lets me interact with files that you personally have created with ESD, which creates a minefield of potential errors when calling Google's services. I have to counteract this with lots of `try-catch` statements (made even better because now the export method has to be async).  I believe there is some potential way to get around this using the google file picker but, like the Drive API, documentation is somewhat lacking so I have to go forum spelunking. Posts [like this](https://www.googlecloudcommunity.com/gc/Workspace-Q-A/Drive-API-Auth-Scope-Changes-Handling-Changing-Remvoing-Scopes/m-p/674909) make me a little worried, but I'm optimistic I can get things working.

My plan for now is to remove the `Replace existing file(s)` and `Export Folder` settings to get an updated build out the door so people can actually use ESD again. This does mean that exported files will be dumped into your root `My Drive` folder for the time being, but it's better than nothing. Fortunately I was able to keep the post-export modal popup functionality, so you will still see links to the exported file and a download button to get it. Just keep an eye on your root folder so you don't drown in `.json` and `.xml` files...

I'm going to take a couple more days to try and get the picker working, but I'm hoping ESD will be back up within a week after making all these changes.

**Comment by Synthoid** [comment]
Hello all! This will hopefully be the last dev update on this ticket before release. Thank you for being so patient!

I believe I have everything working now, including custom export locations and replacing existing files. To compensate for the new workflows, I've updated a lot of the sidebar's code to be more responsive and cleaner for long term maintenance. There will be some structural differences in settings, mostly due to how OAuth workflows are required to work, but I have taken steps to persist as many existing settings as possible.

Anyway, I'm going to take a few more days to finish cleaning up the new code and bug test to make sure everything is working properly. I'm aiming to submit ESD for review by the end of the week, so if everything goes smoothly it should be working for everyone sometime next week.

Again, I'm sorry that it took so long to get things up and running and I appreciate everyone's patience!

**Comment by sfrunaway** [comment]
Thanks Chris!

**Comment by sebinfinity** [comment]
Thank you!

**Comment by adrileo3** [comment]
Thanks Synthoid, hope it works soon!

**Comment by Synthoid** [comment]
One more quick update, since I'm a little behind on my promised delivery.

I've tested everything, and ESD seems to be bug free and 99% ready to submit for review. I'm currently updating screenshots for the add-ons browser listing since those are horribly out of date. Once that is done, I have a small adjustment to make on how custom export location/replace file target settings are stored, then ESD should be ready for review! If I don't get that submitted by tonight, it should be ready by EOD tomorrow.

Sorry for the short delay. I'll post any updates if Google approves or rejects the new submission, but I'm optimistic that you will all have access this week.

**Comment by Synthoid** [comment]
> Thank you for your patience while we reviewed your submission. We've approved your OAuth App Verification request...

With that, I believe [v66](https://github.com/Synthoid/ExportSheetData/releases/tag/v66) is live! I was able to export a sheet, formatting and all. Being paranoid, I'll keep this ticket open for a little longer until I have some external confirmation that it's working...

Let me know if that isn't working for anyone!

**Comment by sfrunaway** [comment]
Looking good here, thanks again Chris!

**Comment by Synthoid** [comment]
Groovy! Thanks for all the patience and support everyone!

![vb_party](https://github.com/user-attachments/assets/cfa538a4-2796-4838-b611-771efbd40d07)
