### ISSUE TITLE
Save the settings

### ISSUE THREAD

**Issue by MauroG** [Synthoid/ExportSheetData#27]
It would be better if we could save the chosen options in Sidebar

**Comment by Synthoid** [comment]
This would be the preferable way to save settings, but it is surprisingly difficult to actually do so. Google add-ons are basically refreshed every time they run so any changes in the script itself would be cleared. The sidebar is regenerated from a template HTML when the sidebar is opened as well.

I'm still looking at good ways to accomplish this however.

Also, this issue is already being tracked [here](https://github.com/Synthoid/ExportSheetData/issues/25), so I'm closing this specific ticket. Please post any future comments or ideas there!

**Comment by MauroG** [comment]
Thank you!
