### ISSUE TITLE
Nested json objects

### ISSUE THREAD

**Issue by davidsvson** [Synthoid/ExportSheetData#31]
Thanks for a great product!

I'm trying to create a nested json like this:
`{
  "Kite": {
    "Attach": "a",
    "Flower": "b",
    "NewObject": [
      "c",
      "d"
    ]
  },
  "Snail": {
    "Attach": "d",
    "Flower": [
      "a",
      "b",
      "c"
    ],
    "NewObject": "f"
  }
}`

Is this possible already? 

I was hoping I could have a fixed first column for the keys of the nested objects.

**Comment by Synthoid** [comment]
The level of nesting should be possible with the current version of ESD (v37), though only if these values make up the entirety of your exported data. You would place each object ("Kite", "Snail", etc) in its own sheet then fill all of the desired fields. This will separate your sheets into separate JSON objects, each identified by the name of the sheet, and would allow for array elements like the ones you posted.

If you want this data to be nested into a parent JSON object called "Objects" (or whatever name you choose), you will unfortunately have to wait until I fully implement [complex nesting behaviors](https://github.com/Synthoid/ExportSheetData/issues/19).

For now, I'm going to close this issue since it is either already possible, or a duplicate issue. If you have any questions or ideas for nested element behavior, check out the issue linked to above or the issue for [sequential complex elements](https://github.com/Synthoid/ExportSheetData/issues/29). Hope that helps!
