### ISSUE TITLE
Nested Elements (JSON/XML) exports only 1 row

### ISSUE THREAD

**Issue by blokhutwinkel** [Synthoid/ExportSheetData#43]
When the nested elements option is enabled the export only exports the last row in the sheet.

**Comment by Synthoid** [comment]
Would you mind posting what your key values are? This sounds like a key path formatting issue.

**Comment by blokhutwinkel** [comment]
item1 | item2 | item3 | [nested]item1 | [nested]item2
1 | 2 | 3 | n1 | n2
4 | 5 | 6 | n1 | n2

results in

{
  "item1": 4,
  "item2": 5,
  "item3": 6,
  "nested": []
}

**Comment by blokhutwinkel** [comment]
maybe it's an idea to add a example sheet for nested items on the wiki

**Comment by Synthoid** [comment]
An example sheet is a good idea. I’ll see if I can get one up today.

As for your issue, it does look like a pathing issue. Nested elements work by starting at the root sheet JSON object then navigating around it based on the paths set up by your keys. Your first key is just trying to access the field ‘item1’ on the root JSON object, so that value will be rewritten each row (since JSON doesn’t support two fields with the same name). Your third and fourth keys will both look for an array called ‘nested’ then for the first array element with a field called ‘item1’. If no element with that field is found, it should add a new element and set that field value. That it’s exporting an empty array is troubling for me, so I’ll take a closer look at it as soon as possible.

Also, are you trying to export your rows to a sheet array? Or are you only doing nesting?

**Comment by blokhutwinkel** [comment]
this is a simple example, also what the expected output should be;


item1 | item2 | item3 | {nested}test
-- | -- | -- | --
1 | 2 | 3 | n1
4 | 5 | 6 | n3

settings: format; JSON, select sheets; Current sheet only, only Nested Elements is checked.

output:

{
  "item1": 4,
  "item2": 5,
  "item3": 6,
  "nested": {
    "test": "n3"
  }
}

expected output:

{
  "item1": 1,
  "item2": 2,
  "item3": 3,
  "nested": {
    "test": "n1"
  }
}
{
  "item1": 4,
  "item2": 5,
  "item3": 6,
  "nested": {
    "test": "n3"
  }
}

**Comment by Synthoid** [comment]
I've put together an [example sheet](https://docs.google.com/spreadsheets/d/1DjXA7ue_fnqe6gYGwl2TJenzOek7Y-9h_Rplx9aGdHU/edit?usp=sharing). It shows how to use a variety of nested element syntax.

As for your most recent test, everything looks correct. If you don't export a sheet array or nest using specific indexes, the keys will just overwrite each other until the last row is reached.

**Comment by blokhutwinkel** [comment]
thanks, the example sheets clears things up.
