### ISSUE TITLE
[JSON] Only exports distinctive columns 

### ISSUE THREAD

**Issue by ZoomImpulse** [Synthoid/ExportSheetData#44]
I noticed something critical, that wasn't there a few months ago. When i try to export a sheet where every column has the same content in the first line, it only exports one of those columns.

**Comment by tareefdev** [comment]
I faced similar problem today, the add-on exports only the last row!

**Comment by Synthoid** [comment]
Hmm, would you mind posting an example of the data you are trying to export, as well as the options you have enabled? Specifically, are you using the new nested elements option?

**Comment by tareefdev** [comment]
This is [the sheet](https://docs.google.com/spreadsheets/d/1RMGIwd1Jkddc1qVg4YvwtCIfhTIirAllld0vfoa6nYw/edit?usp=sharing) that tried to export:

with the following options:
 Replace existing file(s), Newline elements, Unwrap single row sheets, Ignore empty cells

**Comment by Synthoid** [comment]
This makes sense now that I see the data. JSON does **_not_** support multiple sibling elements with the same ID. The new exporter performs JSON validation, so your values would be overridden each row. It was working before because the exported data was likely malformed JSON. That was a significant oversight in the system and I apologize for my past negligence.

If you want to use your current sheet, I would recommend enabling 'Export sheet arrays'. This should export all of your data in a properly formatted JSON array.

**Comment by tareefdev** [comment]
>  I would recommend enabling 'Export sheet arrays'. 

YES! that's work. thanks a lot.

**Comment by Synthoid** [comment]
Glad to hear that works! I'm going to close this issue, as it is actual a case of the previous version of ESD outputting bad JSON and the new system correcting that mistake.
