### ISSUE TITLE
(General) Collapse single row sheets option

### ISSUE THREAD

**Issue by Synthoid** [Synthoid/ExportSheetData#52]
Add an option to collapse single row sheets.

Unlike unwrapping sheets, where the data from the only row in a sheet is placed into the root of the main JSON blob, this option unwraps the row's JSON so it is in the sheet's JSON content. For example:

Sheet Name: Test

Input:
`Field1 | Field2 | Field3`
`Lupin | false | 0.75`

Default Output:
`{`
`--"Test": {`
`----"Lupin": {`
`------"Field1":"Lupin",`
`------"Field2":false,`
`------"Field3":0.75`
`----}`
`--}`
`}`

Unwrapped Output:
`{`
`--"Field1":"Lupin",`
`--"Field2":false,`
`--"Field3":0.75`
`}`

Collapsed Output:
`{`
`--"Test": {`
`----"Field1":"Lupin",`
`----"Field2":false,`
`----"Field3":0.75`
`--}`
`}`

**Comment by Synthoid** [comment]
Shipped in v44 for JSON. XML support will require nested element implementation.

**Comment by mherbold** [comment]
This is not working for me - my single row sheet still gets exported as an array with this feature turned on.  This used to be what "Unwrap single row sheets" did in an older version (convert to object instead of array) and it worked beautifully then.  In the latest version it does not work any more.  I reported this as an issue here along with a link to my sheet.

**Comment by Synthoid** [comment]
Pushing the v50 update later today that will have XML support for this.
