### ISSUE TITLE
Question: Export Cell Objects

### ISSUE THREAD

**Issue by oneezy** [Synthoid/ExportSheetData#58]
I'm having trouble [exporting cell objects](https://github.com/Synthoid/ExportSheetData/blob/b85db32011ac829885d8cb8f9ae58f7d9021f159/docs/json/exportcellobjects.md) from the documenation instructions... Can you please explain how to do it properly?

**Comment by oneezy** [comment]
If anyone else is wondering how to do this:

1. Make sure you have **Export cell objects** checked in the sidebar
2. Write your object in the cell like this `{ "Key1": "Value 1", "Key2": "Value 2", "Key3": "value 3" }`

**JSON Output** [(Google Sheet Example)](https://docs.google.com/spreadsheets/d/137_MYe-0iDvnG2f4DBsEVaOLgwHIW5PQRHz1Duq_5F4/edit?usp=sharing)

```
{
  "data-1": {
    "ID1": {
      "ID": "ID1",
      "CLASS": "class-1",
      "EXPORT CELL OBJECT": {
        "Key1": "Value 1",
        "Key2": "Value 2",
        "Key3": "value 3"
      }
    },
    "ID2": {
      "ID": "ID2",
      "CLASS": "class-2",
      "EXPORT CELL OBJECT": {
        "Key1": "Value 1",
        "Key2": "Value 2",
        "Key3": "value 3"
      }
    },
    "ID3": {
      "ID": "ID3",
      "CLASS": "class-3",
      "EXPORT CELL OBJECT": {
        "Key1": "Value 1",
        "Key2": "Value 2",
        "Key3": "value 3"
      }
    }
  }
}
```

**Comment by Synthoid** [comment]
Sorry for the delayed response. I’m currently traveling so it’s difficult to do my usual GitHub management.

In order to export cell objects. You must write valid JSON directly into a cell. This means open and close braces ( { and } ) as well as properly formatted field names wrapped with quotes and colons separating keys from values.

if the JSON entered is not valid, an empty JSON object ( {} )will be added to your export instead.
