### ISSUE TITLE
Bug in apostrophe encoding

### ISSUE THREAD

**Issue by basalicante** [Synthoid/ExportSheetData#77]
First of all, thank for your great work. I'm using it all the time!

Found a bug in the export of apostrophes to xml, they get encoded as `&amp;apos;` rather than `&apos;` 

Attaching an image as an example.

Thanks!

![image](https://user-images.githubusercontent.com/8726066/49657826-de589b80-fa40-11e8-8b14-a05fc5754bac.png)

**Comment by Youwza** [comment]
Also "&" gets encoded as `&amp;amp;` instead of `&amp;`

Thank you so much for the plugin!

**Comment by Synthoid** [comment]
Just pushed v52 which should fix this issue. The problem was that the new backend for exporting XML always encodes characters, causing them to be double encoded.

Unfortunately, this means the "Don't format illegal characters" option is no longer functional and has been removed. Apostrophes are no longer encoded either because this. Fortunately, apostrophe encoding is only needed when values are wrapped with single quotes, which is impossible here.
