### ISSUE TITLE
Nested json objects with contents as array

### ISSUE THREAD

**Issue by GabrielRodriguesS** [Synthoid/ExportSheetData#86]
### Scenario: 
![image](https://user-images.githubusercontent.com/15824190/56610105-1b36c080-65e5-11e9-854c-0cc7c7aa4c37.png)
Only check "Nested Elements" option and Current Sheet Only.
### Result:
Only one element was converted:
![image](https://user-images.githubusercontent.com/15824190/56610214-50dba980-65e5-11e9-8147-f08f748ca862.png)
### Expected:
![image](https://user-images.githubusercontent.com/15824190/56610579-263e2080-65e6-11e9-8620-a13dcc09b75a.png)

How to fix it?

**Comment by Synthoid** [comment]
To export nested arrays you have to use specific formatting on the keys, otherwise the exported rows will keep overwriting each other. I recommend looking at the documentation for the [Nested array prefix](https://github.com/Synthoid/ExportSheetData/blob/master/docs/json/nestedarrayprefix.md) option and looking at the wiki page for nested elements in general. But just enabling the Nested array prefix option and adding the appropriate prefix to your sheet name should take care of the issue.

**Comment by mikelga** [comment]
Hi @GabrielRodriguesS I think that I have the same problem. Have you solve it?

**Comment by GabrielRodriguesS** [comment]
I put the matrix prefix and nothing.
I told you how it was as soon as possible.

**Comment by GabrielRodriguesS** [comment]
Giving up, it was simpler to tweak the data using a programming language.
