### ISSUE TITLE
Extension offline

### ISSUE THREAD

**Issue by lemalsaint** [Synthoid/ExportSheetData#89]
Hi guys - I can't find your extension in the Chrome App Store anymore?
The link (https://chrome.google.com/webstore/detail/export-sheet-data/bfdcopkbamihhchdnjghdknibmcnfplk?hl=en) 
routes me to nowhere. 
Can it still be installed? 

Thanks for your help,

Oliver

**Comment by Synthoid** [comment]
Hmm, it seems to be redirecting to the G Suite marketplace now? I just updated ESD to support G Suite a few weeks ago, so it would seem that it is in a weird limbo currently. I'll have to contact someone at Google to ask about it, since I don't have any messages from them stating ESD's marketplace review process had failed.

For now, it looks like you can still install ESD by manually searching for it in Sheet's "Add-ons/Get add-ons..." menu item. Sorry for the inconvenience!

**Comment by lemalsaint** [comment]
Fantastic, thank you! This issue was more supposed to make everybody aware!
