### ISSUE TITLE
null instead of "null"

### ISSUE THREAD

**Issue by 926** [Synthoid/ExportSheetData#94]
This repo is amazing, thank you so much for building this,
Please could you tell me how we can have __null__ without coma, 
The same way that true is exported :

This is what I get : 
    "dlc": "null",
    "quantity": 0,
    "isDefault": true

This is what we need : 
    "dlc": null,
    "quantity": 0,
    "isDefault": true

**Comment by 926** [comment]
/src/ExportSheetData.gs

l319    else if(cellArray[i] === 'true') cellArray[i] = true;
l320    else if(cellArray[i] === 'false') cellArray[i] = false;

does it solve it if we add :
l321 else if(cellArray[i] === 'null') cellArray[i] = null;

**Comment by Synthoid** [comment]
Currently, any values entered into cells are interpreted as-is. A cell with the value `null` entered is interpreted as the string `"null"` because as far the cell is concerned, there is a string value inside it. You can leave the field empty and set the [empty value format](https://github.com/Synthoid/ExportSheetData/blob/master/docs/json/emptyvalueformat.md) to null values to do what you want. It may be good to allow users to enter `null` to create a null value though.

**Comment by 926** [comment]
Thank you for the quick reply,
Problem is I need to use the "ignore empty cell",
So the empty value format cannot be used,

It would be good to allow users, including myself, to enter null
This project is already a life-saver for our us,
If there is anything I can do, blog publicity, testimony, please let me know by PM

**Comment by Synthoid** [comment]
Sorry for the delayed response. I think I can add a feature similar to the bool checks where `null` is translated as a null value, while `"null"` is translated as the string `null`. I'll mess around with it and try to get something posted next week.

**Comment by 926** [comment]
Amazing, thanks a lot !

**Comment by Synthoid** [comment]
Sorry it took longer than expected, but [this is available as of v57](https://github.com/Synthoid/ExportSheetData/blob/master/docs/json/nullvalueformat.md).

**Comment by 926** [comment]
Well done, I owe you a bif coffee ;)
